CREATE TABLE bookmarks_list (
  id INTEGER primary key generated by default as identity,
  title text NOT NULL,
  url text NOT NULL,
  description text,
  rating INTEGER NOT NULL,
  CONSTRAINT rating_chk CHECK (rating BETWEEN 1 AND 5)
);